### ISSUE TITLE
Building errors

### ISSUE THREAD

**Issue by sLaera** [raphaelsulzer/mesh-tools#2]
I've installed all the required dependencies and then built the project with:
```
mkdir build && cd build
cmake .. -DCMAKE_BUILD_TYPE=RELEASE
make -j
```
I encountered several build errors (I'm pasting only the error logs here):
```
/home/usr/mesh-tools/src/processing/evaluation.cpp:115:15: error: ‘AABB_traits’ in namespace ‘CGAL’ does not name a template type; did you mean ‘AABB_traits_3’?
  115 | typedef CGAL::AABB_traits<EPICK, Primitive> Traits;
      |               ^~~~~~~~~~~

/home/usr/mesh-tools/src/processing/evaluation.cpp:116:25: error: ‘Traits’ was not declared in this scope
  116 | typedef CGAL::AABB_tree<Traits> Tree;
      |                         ^~~~~~

/home/usr/mesh-tools/src/processing/evaluation.cpp:116:31: error: template argument 1 is invalid
  116 | typedef CGAL::AABB_tree<Traits> Tree;
      |                               ^

/home/usr/mesh-tools/src/processing/evaluation.cpp:117:38: error: expected initializer before ‘Point_and_primitive_id’
  117 | typedef Tree::Point_and_primitive_id Point_and_primitive_id;
      |                                      ^~~~~~~~~~~~~~~~~~~~~~

/home/usr/mesh-tools/src/processing/evaluation.cpp:118:71: error: template argument 1 is invalid
  118 | typedef boost::optional<Tree::Intersection_and_primitive_id<Ray>::Type> Ray_intersection;
      |                                                                       ^

/home/usr/mesh-tools/src/processing/evaluation.cpp:166:55: error: expression list treated as compound expression in initializer [-fpermissive]
  166 |     Tree gt_tree(faces(gt).first, faces(gt).second, gt);
      |                                                       ^

/home/usr/mesh-tools/src/processing/evaluation.cpp:166:55: error: cannot convert ‘Polyhedron’ {aka ‘CGAL::Polyhedron_3<CGAL::Epick, CGAL::Polyhedron_items_with_id_3>’} to ‘Tree’ {aka ‘int’} in initialization
/home/usr/mesh-tools/src/processing/evaluation.cpp:167:13: error: request for member ‘accelerate_distance_queries’ in ‘gt_tree’, which is of non-class type ‘Tree’ {aka ‘int’}
  167 |     gt_tree.accelerate_distance_queries();
      |             ^~~~~~~~~~~~~~~~~~~~~~~~~~~

/home/usr/mesh-tools/src/processing/evaluation.cpp:168:48: error: no matching function for call to ‘CGAL::Side_of_triangle_mesh<CGAL::Polyhedron_3<CGAL::Epick, CGAL::Polyhedron_items_with_id_3>, CGAL::Epick>::Side_of_triangle_mesh(Tree&)’
  168 |     const Point_inside gt_inside_tester(gt_tree);
      |                                                ^

/home/usr/mesh-tools/src/processing/evaluation.cpp:171:67: error: expression list treated as compound expression in initializer [-fpermissive]
  171 |     Tree recon_tree(faces(recon).first, faces(recon).second, recon);
      |                                                                   ^

/home/usr/mesh-tools/src/processing/evaluation.cpp:171:67: error: cannot convert ‘Polyhedron’ {aka ‘CGAL::Polyhedron_3<CGAL::Epick, CGAL::Polyhedron_items_with_id_3>’} to ‘Tree’ {aka ‘int’} in initialization
/home/usr/mesh-tools/src/processing/evaluation.cpp:172:16: error: request for member ‘accelerate_distance_queries’ in ‘recon_tree’, which is of non-class type ‘Tree’ {aka ‘int’}
  172 |     recon_tree.accelerate_distance_queries();
      |                ^~~~~~~~~~~~~~~~~~~~~~~~~~~

/home/usr/mesh-tools/src/processing/evaluation.cpp:173:54: error: no matching function for call to ‘CGAL::Side_of_triangle_mesh<CGAL::Polyhedron_3<CGAL::Epick, CGAL::Polyhedron_items_with_id_3>, CGAL::Epick>::Side_of_triangle_mesh(Tree&)’
  173 |     const Point_inside recon_inside_tester(recon_tree);
      |                                                      ^

/home/usr/mesh-tools/src/processing/evaluation.cpp:212:15: error: ‘AABB_traits’ in namespace ‘CGAL’ does not name a template type; did you mean ‘AABB_traits_3’?
  212 | typedef CGAL::AABB_traits<EPICK, Primitive> Traits;
      |               ^~~~~~~~~~~

/home/usr/mesh-tools/src/processing/evaluation.cpp:213:25: error: ‘Traits’ was not declared in this scope
  213 | typedef CGAL::AABB_tree<Traits> PolyhedronTree;
      |                         ^~~~~~

/home/usr/mesh-tools/src/processing/evaluation.cpp:213:31: error: template argument 1 is invalid
  213 | typedef CGAL::AABB_tree<Traits> PolyhedronTree;
      |                               ^

/home/usr/mesh-tools/src/processing/evaluation.cpp:214:38: error: expected initializer before ‘Point_and_primitive_id’
  214 | typedef Tree::Point_and_primitive_id Point_and_primitive_id;
      |                                      ^~~~~~~~~~~~~~~~~~~~~~

/home/usr/mesh-tools/src/processing/evaluation.cpp:215:71: error: template argument 1 is invalid
  215 | typedef boost::optional<Tree::Intersection_and_primitive_id<Ray>::Type> Ray_intersection;
      |                                                                       ^

/home/usr/mesh-tools/src/processing/evaluation.cpp:260:95: error: expression list treated as compound expression in initializer [-fpermissive]
  260 |     PolyhedronTree gt_tree(faces(data.gt_poly).first, faces(data.gt_poly).second, data.gt_poly);
      |                                                                                               ^

/home/usr/mesh-tools/src/processing/evaluation.cpp:260:95: error: cannot convert ‘Polyhedron’ {aka ‘CGAL::Polyhedron_3<CGAL::Epick, CGAL::Polyhedron_items_with_id_3>’} to ‘PolyhedronTree’ {aka ‘int’} in initialization
/home/usr/mesh-tools/src/processing/evaluation.cpp:261:13: error: request for member ‘accelerate_distance_queries’ in ‘gt_tree’, which is of non-class type ‘PolyhedronTree’ {aka ‘int’}
  261 |     gt_tree.accelerate_distance_queries();
      |             ^~~~~~~~~~~~~~~~~~~~~~~~~~~

/home/usr/mesh-tools/src/processing/evaluation.cpp:262:48: error: no matching function for call to ‘CGAL::Side_of_triangle_mesh<CGAL::Polyhedron_3<CGAL::Epick, CGAL::Polyhedron_items_with_id_3>, CGAL::Epick>::Side_of_triangle_mesh(PolyhedronTree&)’
  262 |     const Point_inside gt_inside_tester(gt_tree);
      |                                                ^

/home/usr/mesh-tools/src/learning/learning.h:14:15: error: ‘AABB_traits’ in namespace ‘CGAL’ does not name a template type; did you mean ‘AABB_traits_3’?
   14 | typedef CGAL::AABB_traits<EPICK, Primitive> AABB_Traits;
      |               ^~~~~~~~~~~

/home/usr/mesh-tools/src/learning/learning.h:15:25: error: ‘AABB_Traits’ was not declared in this scope
   15 | typedef CGAL::AABB_tree<AABB_Traits> Tree;
      |                         ^~~~~~~~~~~

/home/usr/mesh-tools/src/learning/learning.h:15:36: error: template argument 1 is invalid
   15 | typedef CGAL::AABB_tree<AABB_Traits> Tree;
      |                                    ^

/home/usr/mesh-tools/src/learning/learning.h:16:38: error: expected initializer before ‘Point_and_primitive_id’
   16 | typedef Tree::Point_and_primitive_id Point_and_primitive_id;
      |                                      ^~~~~~~~~~~~~~~~~~~~~~

/home/usr/mesh-tools/src/learning/learning.h:17:71: error: template argument 1 is invalid
   17 | typedef boost::optional<Tree::Intersection_and_primitive_id<Ray>::Type> Ray_intersection;
      |                                                                       ^

/home/usr/mesh-tools/src/learning/learning.cpp:68:44: error: expression list treated as compound expression in initializer [-fpermissive]
   68 |     Tree tree(fds.begin(), fds.end(), smesh);
      |                                            ^

/home/usr/mesh-tools/src/learning/learning.cpp:68:44: error: cannot convert ‘SurfaceMesh’ {aka ‘CGAL::Surface_mesh<CGAL::Point_3<CGAL::Epick> >’} to ‘Tree’ {aka ‘int’} in initialization
/home/usr/mesh-tools/src/learning/learning.cpp:69:10: error: request for member ‘accelerate_distance_queries’ in ‘tree’, which is of non-class type ‘Tree’ {aka ‘int’}
   69 |     tree.accelerate_distance_queries();
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~

/home/usr/mesh-tools/src/learning/learning.cpp:122:26: error: request for member ‘number_of_intersected_primitives’ in ‘tree’, which is of non-class type ‘Tree’ {aka ‘int’}
  122 |             int n = tree.number_of_intersected_primitives(seg);
      |                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

/home/usr/mesh-tools/src/learning/learning.cpp:201:61: error: expression list treated as compound expression in initializer [-fpermissive]
  201 |     Tree tree(faces(smesh).first, faces(smesh).second, smesh);
      |                                                             ^

/home/usr/mesh-tools/src/learning/learning.cpp:201:61: error: cannot convert ‘SurfaceMesh’ {aka ‘CGAL::Surface_mesh<CGAL::Point_3<CGAL::Epick> >’} to ‘Tree’ {aka ‘int’} in initialization
/home/usr/mesh-tools/src/learning/learning.cpp:202:10: error: request for member ‘accelerate_distance_queries’ in ‘tree’, which is of non-class type ‘Tree’ {aka ‘int’}
  202 |     tree.accelerate_distance_queries();
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~

/home/usr/mesh-tools/src/learning/learning.cpp:204:40: error: no matching function for call to ‘CGAL::Side_of_triangle_mesh<CGAL::Surface_mesh<CGAL::Point_3<CGAL::Epick> >, CGAL::Epick>::Side_of_triangle_mesh(Tree&)’
  204 |     const Point_inside inside_mesh(tree);
      |                                        ^

/home/usr/mesh-tools/src/learning/learning.cpp:309:61: error: expression list treated as compound expression in initializer [-fpermissive]
  309 |     Tree tree(faces(smesh).first, faces(smesh).second, smesh);
      |                                                             ^

/home/usr/mesh-tools/src/learning/learning.cpp:309:61: error: cannot convert ‘SurfaceMesh’ {aka ‘CGAL::Surface_mesh<CGAL::Point_3<CGAL::Epick> >’} to ‘Tree’ {aka ‘int’} in initialization
/home/usr/mesh-tools/src/learning/learning.cpp:311:10: error: request for member ‘accelerate_distance_queries’ in ‘tree’, which is of non-class type ‘Tree’ {aka ‘int’}
  311 |     tree.accelerate_distance_queries();
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~

/home/usr/mesh-tools/src/learning/learning.cpp:313:42: error: no matching function for call to ‘CGAL::Side_of_triangle_mesh<CGAL::Surface_mesh<CGAL::Point_3<CGAL::Epick> >, CGAL::Epick>::Side_of_triangle_mesh(Tree&)’
  313 |     const Point_inside inside_tester(tree);
      |                                          ^

/home/usr/mesh-tools/src/processing/meshProcessing.cpp:168:15: error: ‘AABB_traits’ in namespace ‘CGAL’ does not name a template type; did you mean ‘AABB_traits_3’?
  168 | typedef CGAL::AABB_traits<EPICK, Primitive> AABB_Traits;
      |               ^~~~~~~~~~~

/home/usr/mesh-tools/src/processing/meshProcessing.cpp:169:25: error: ‘AABB_Traits’ was not declared in this scope
  169 | typedef CGAL::AABB_tree<AABB_Traits> Tree;
      |                         ^~~~~~~~~~~

/home/usr/mesh-tools/src/processing/meshProcessing.cpp:169:36: error: template argument 1 is invalid
  169 | typedef CGAL::AABB_tree<AABB_Traits> Tree;
      |                                    ^

/home/usr/mesh-tools/src/processing/meshProcessing.cpp:170:38: error: expected initializer before ‘Point_and_primitive_id’
  170 | typedef Tree::Point_and_primitive_id Point_and_primitive_id;
      |                                      ^~~~~~~~~~~~~~~~~~~~~~

/home/usr/mesh-tools/src/processing/meshProcessing.cpp:172:71: error: template argument 1 is invalid
  172 | typedef std::optional< Tree::Intersection_and_primitive_id<Ray>::Type > Ray_intersection;
      |                                                                       ^

/home/usr/mesh-tools/src/processing/meshProcessing.cpp:202:61: error: expression list treated as compound expression in initializer [-fpermissive]
  202 |     Tree tree(faces(smesh).first, faces(smesh).second, smesh);
      |                                                             ^

/home/usr/mesh-tools/src/processing/meshProcessing.cpp:202:61: error: cannot convert ‘SurfaceMesh’ {aka ‘CGAL::Surface_mesh<CGAL::Point_3<CGAL::Epick> >’} to ‘Tree’ {aka ‘int’} in initialization
/home/usr/mesh-tools/src/processing/meshProcessing.cpp:204:10: error: request for member ‘accelerate_distance_queries’ in ‘tree’, which is of non-class type ‘Tree’ {aka ‘int’}
  204 |     tree.accelerate_distance_queries();
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~

/home/usr/mesh-tools/src/processing/meshProcessing.cpp:261:46: error: request for member ‘first_intersection’ in ‘tree’, which is of non-class type ‘Tree’ {aka ‘int’}
  261 |         Ray_intersection intersection = tree.first_intersection(ray);
      |                                              ^~~~~~~~~~~~~~~~~~

/home/usr/mesh-tools/src/processing/meshProcessing.cpp:263:47: error: base operand of ‘->’ is not a pointer
  263 |           if(std::get_if<Point>(&(intersection->first))){
      |                                               ^~

/home/usr/mesh-tools/src/processing/meshProcessing.cpp:264:63: error: base operand of ‘->’ is not a pointer
  264 |             const Point* p = std::get_if<Point>(&(intersection->first) );
      |                                                               ^~

/home/usr/mesh-tools/src/processing/meshProcessing.cpp:265:35: error: base operand of ‘->’ is not a pointer
  265 |             auto fd = intersection->second;
      |                                   ^~

/home/usr/mesh-tools/src/processing/meshProcessing.cpp:367:61: error: expression list treated as compound expression in initializer [-fpermissive]
  367 |     Tree tree(faces(smesh).first, faces(smesh).second, smesh);
      |                                                             ^

/home/usr/mesh-tools/src/processing/meshProcessing.cpp:367:61: error: cannot convert ‘SurfaceMesh’ {aka ‘CGAL::Surface_mesh<CGAL::Point_3<CGAL::Epick> >’} to ‘Tree’ {aka ‘int’} in initialization
/home/usr/mesh-tools/src/processing/meshProcessing.cpp:368:10: error: request for member ‘accelerate_distance_queries’ in ‘tree’, which is of non-class type ‘Tree’ {aka ‘int’}
  368 |     tree.accelerate_distance_queries();
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~

/home/usr/mesh-tools/src/processing/meshProcessing.cpp:389:42: error: no matching function for call to ‘CGAL::Side_of_triangle_mesh<CGAL::Surface_mesh<CGAL::Point_3<CGAL::Epick> >, CGAL::Epick>::Side_of_triangle_mesh(Tree&)’
  389 |     const Point_inside inside_tester(tree);
      |                                          ^

/home/usr/mesh-tools/src/processing/meshProcessing.cpp:429:46: error: request for member ‘first_intersection’ in ‘tree’, which is of non-class type ‘Tree’ {aka ‘int’}
  429 |         Ray_intersection intersection = tree.first_intersection(ray);
      |                                              ^~~~~~~~~~~~~~~~~~

/home/usr/mesh-tools/src/processing/meshProcessing.cpp:431:47: error: base operand of ‘->’ is not a pointer
  431 |           if(std::get_if<Point>(&(intersection->first))){
      |                                               ^~

/home/usr/mesh-tools/src/processing/meshProcessing.cpp:433:63: error: base operand of ‘->’ is not a pointer
  433 |             const Point* p = std::get_if<Point>(&(intersection->first) );
      |                                                               ^~

/home/usr/mesh-tools/src/processing/meshProcessing.cpp:434:35: error: base operand of ‘->’ is not a pointer
  434 |             auto fd = intersection->second;
      |                                   ^~

/home/usr/mesh-tools/src/learning/learning.h:14:15: error: ‘AABB_traits’ in namespace ‘CGAL’ does not name a template type; did you mean ‘AABB_traits_3’?
   14 | typedef CGAL::AABB_traits<EPICK, Primitive> AABB_Traits;
      |               ^~~~~~~~~~~

/home/usr/mesh-tools/src/learning/learning.h:15:25: error: ‘AABB_Traits’ was not declared in this scope
   15 | typedef CGAL::AABB_tree<AABB_Traits> Tree;
      |                         ^~~~~~~~~~~

/home/usr/mesh-tools/src/learning/learning.h:15:36: error: template argument 1 is invalid
   15 | typedef CGAL::AABB_tree<AABB_Traits> Tree;
      |                                    ^

/home/usr/mesh-tools/src/learning/learning.h:16:38: error: expected initializer before ‘Point_and_primitive_id’
   16 | typedef Tree::Point_and_primitive_id Point_and_primitive_id;
      |                                      ^~~~~~~~~~~~~~~~~~~~~~

/home/usr/mesh-tools/src/learning/learning.h:17:71: error: template argument 1 is invalid
   17 | typedef boost::optional<Tree::Intersection_and_primitive_id<Ray>::Type> Ray_intersection;
      |                                                                       ^

```

I'm probably missing something

**Comment by raphaelsulzer** [comment]
I assume this comes from a CGAL version mismatch. Which CGAL version are you using?

**Comment by sLaera** [comment]
I'm using CGAL-6.0.1 from `https://github.com/CGAL/cgal/releases/download/v6.0.1/CGAL-6.0.1.tar.xz`.
I've built it from source

**Comment by raphaelsulzer** [comment]
OK, I'll try to update the code. It doesn't even compile on CGAL 5.6.1.

**Comment by sLaera** [comment]
Ok, thank you.
Let me know which CGAL version should I use.

**Comment by sLaera** [comment]
I don't know if this might help, but I found a quick way to make it compile. I only tested the scan function, though:

I replaced all instances of `CGAL::AABB_traits` with `CGAL::AABB_traits_3`, and I edited line 229 in the file `processing/pointSetProcessing.cpp` as follows:
```cpp
// - Point_set::Property_map<double> noise = point_set.property_map<double>("noise").first;

auto noise_opt = point_set.property_map<double>("noise");

if (!noise_opt.has_value()) {
    throw std::runtime_error("Property 'noise' not found in point set.");
}

Point_set::Property_map<double> noise = noise_opt.value();
```
Again, I didn't test this function specifically, but I think this could work.

**Comment by raphaelsulzer** [comment]
Great, thank you. I will push the fix. The `scan` module is all you need for the `dsr-benchmark`.
